apiVersion: v1
kind: Pod
metadata:
  name: pod-invalid-ratio
spec:
  containers:
    - name: nginx
      image: nginx
      resources:
        requests:
          memory: "300Mi"
        limits:
          memory: "200Mi"